// <auto-generated />
namespace ERP_BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixedAssetClassMappingAdjusted03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedAssetClassMappingAdjusted03));
        
        string IMigrationMetadata.Id
        {
            get { return "202005021222590_FixedAssetClassMappingAdjusted03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
