// <auto-generated />
namespace ERP_BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LoanChanges18122021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LoanChanges18122021));
        
        string IMigrationMetadata.Id
        {
            get { return "202112181205523_LoanChanges18122021"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
