// <auto-generated />
namespace ERP_BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changesInRentalModule09172021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changesInRentalModule09172021));
        
        string IMigrationMetadata.Id
        {
            get { return "202109171228548_changesInRentalModule09172021"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
