// <auto-generated />
namespace ERP_BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Company_InsertAndCompany_UpdateAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Company_InsertAndCompany_UpdateAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202201221551075_Company_InsertAndCompany_UpdateAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
