// <auto-generated />
namespace ERP_BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class receiptGroupIdAddedInJournalVouchers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(receiptGroupIdAddedInJournalVouchers));
        
        string IMigrationMetadata.Id
        {
            get { return "202206301258005_receiptGroupIdAddedInJournalVouchers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
