// <auto-generated />
namespace ERP_BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TargetRewardNaturesAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TargetRewardNaturesAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202505211607431_TargetRewardNaturesAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
